name: Build and Release APK

permissions:
  contents: write
  issues: write
  pull-requests: write
  actions: read
  deployments: write

on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Cache Gradle
        uses: actions/cache@v4.1.2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Decode keystore
        run: echo "$KEYSTORE_FILE" | base64 --decode > ${{ github.workspace }}/composeApp/keystore.jks
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4.4.3
        with:
          name: CoolTimer.apk
          path: composeApp/build/outputs/apk/release/composeApp-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes
            - Reduced APK size.
            
            https://github.com/IvanCaEz/MultiplatformTimer/assets/125135728/ddeac788-c3f2-4639-9eea-481222bb1bad
            
            **Full Changelog**: ${{ env.changelog }}
          artifacts: composeApp/build/outputs/apk/release/composeApp-release.apk
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN  }}